#!/bin/bash
#SBATCH --job-name=train_prc_emo_qwen25_omni
#SBATCH --output=/scratch/data/bikash_rs/Vivek/PRC-Emo/logs/%x_%j.out
#SBATCH --error=/scratch/data/bikash_rs/Vivek/PRC-Emo/logs/%x_%j.err
#SBATCH --partition=dgx
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=2-00:00:00
#SBATCH --qos=fatqos
#SBATCH -D /scratch/data/bikash_rs/Vivek/PRC-Emo

# Create logs directory
mkdir -p logs

# Load CUDA module (adjust version based on your system)
# module load cuda/11.8

# Activate virtual environment
source prc-emo-omni-env/bin/activate

EP=4
BN=2
CPE=1
LR_SCHEDULER="linear"
LR=2e-4
LORA_R=32
TOPK=0
WINDOW=5


# spdescV2: Generate speaker features
# default: Generate nothing
# ImplicitEmotion: Use implicit emotion labels and their descriptions
# ImplicitEmotion_V2: Use explicit emotion descriptions and implicit emotion descriptions, generated by Qwen2.5
# ImplicitEmotion_V2_byQwen3_14b: Use explicit emotion descriptions and implicit emotion descriptions (30-50 words), generated by Qwen3-14b
# ImplicitEmotion_V3: Replace SurfaceEmotion with ExplicitEmotion (30-50 words), generated by Qwen3-14b with a window size of 10
# spdescV3: 100-word background summary and speaker summary, generated by Qwen14b
# spdescV4: 250-word background summary and speaker summary, generated by Qwen14b
# spdescV5: 250-word speaker personality description, generated by Qwen14b
# spdescV6: 100-word speaker personality description, generated by Qwen14b

#spdescV2: 生成说话人特征
#default: 啥也不生成
#ImplicitEmotion: 使用隐性情绪标签以及其描述
#ImplicitEmotion_V2: 使用显性情绪描述和隐性情绪描述。通过Qwen2.5
#ImplicitEmotion_V2_byQwen3_14b: 使用显性情绪描述和隐性情绪描述(30-50词)。通过Qwen3-14b
#ImplicitEmotion_V3: 替换SurfaceEmotion为ExplicitEmotion(30-50词)。通过Qwen3-14b，窗口为10
#spdescV3: 100词的背景概要和说话人概要，Qwen14b
#spdescV4: 250词的背景概要和说话人概要，Qwen14b
#spdescV5: 250词的说话人性格，Qwen14b
#spdescV6: 100词的说话人性格，Qwen14b

PROMPT_TYPE="ImplicitEmotion_V3" # spdescV2 | default | ImplicitEmotion | ImplicitEmotion_V2 | ImplicitEmotion_V2_byQwen3_14b | ImplicitEmotion_V3 | spdescV3 | spdescV6
MODEL_ID="/scratch/data/bikash_rs/Vivek/PRC-Emo/models/qwen_2_5_omni_7b" # please switch to your own model path if needed
DATANAME="meld"   # meld only for src/ft_llm_qwen25_omni.py
EXTRACT_PROMTING_LLM_ID="qwen_3_14b"
MAX_SEQ_LEN=2048
MAX_STEPS=-1
EVAL_DELAY=100000
VIDEO_FPS=1.0
GENERATION_MAX_NEW_TOKENS=10
PER_DEVICE_TRAIN_BATCH_SIZE=1
GRADIENT_ACCUMULATION_STEPS=4
OPTIM="adamw_torch_fused"

MELD_TRAIN_VIDEO_DIR="/scratch/data/bikash_rs/Vivek/dataset/MELD/MELD.Raw/train_splits"
MELD_VALID_VIDEO_DIR="/scratch/data/bikash_rs/Vivek/dataset/MELD/MELD.Raw/dev_splits_complete"
MELD_TEST_VIDEO_DIR="/scratch/data/bikash_rs/Vivek/dataset/MELD/MELD.Raw/output_repeated_splits_test"
MELD_TRAIN_AUDIO_DIR="/scratch/data/bikash_rs/Vivek/dataset/MELD_audio/train"
MELD_VALID_AUDIO_DIR="/scratch/data/bikash_rs/Vivek/dataset/MELD_audio/dev"
MELD_TEST_AUDIO_DIR="/scratch/data/bikash_rs/Vivek/dataset/MELD_audio/test"

MODEL_ID_0=$(basename "$MODEL_ID")

for seed in 42;
do
python ./src/ft_llm_qwen25_omni.py --do_eval_dev --do_eval_test --do_train --curriculum --bucket_number ${BN} \
 --base_model_id $MODEL_ID --curriculum_update_epochs ${CPE} \
 --ft_model_id ${DATANAME}_${MODEL_ID_0}_ep${EP}_step${MAX_STEPS}_lrs-${LR_SCHEDULER}${LR}_${TOPK}shot_r${LORA_R}_w${WINDOW}_${PROMPT_TYPE}_seed${seed}_L${MAX_SEQ_LEN}_llmdesc${EXTRACT_PROMTING_LLM_ID}_ED${EVAL_DELAY}_omni \
 --lr_scheduler $LR_SCHEDULER --lr $LR --lora_r $LORA_R --max_steps $MAX_STEPS --epoch ${EP} \
 --kshot $TOPK --window $WINDOW --data_name $DATANAME --prompting_type ${PROMPT_TYPE} --extract_prompting_llm_id $EXTRACT_PROMTING_LLM_ID \
 --seed $seed --max_seq_len $MAX_SEQ_LEN --eval_delay $EVAL_DELAY --data_folder ./data/ \
 --video_fps $VIDEO_FPS --generation_max_new_tokens $GENERATION_MAX_NEW_TOKENS \
 --per_device_train_batch_size $PER_DEVICE_TRAIN_BATCH_SIZE --gradient_accumulation_steps $GRADIENT_ACCUMULATION_STEPS \
 --optim $OPTIM \
 --meld_train_video_dir $MELD_TRAIN_VIDEO_DIR --meld_valid_video_dir $MELD_VALID_VIDEO_DIR --meld_test_video_dir $MELD_TEST_VIDEO_DIR \
 --meld_train_audio_dir $MELD_TRAIN_AUDIO_DIR --meld_valid_audio_dir $MELD_VALID_AUDIO_DIR --meld_test_audio_dir $MELD_TEST_AUDIO_DIR
done

wait
